name: Automated Version Bump
description: Automated version bump for npm packages.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: chevron-up
  color: blue
inputs:
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: ''
    required: false
  tag-revision:
    description: 'Set this to true in order to tag this up-rev'
    required: false
  username:
    description: 'set to override GITHUB_USER in the merge commit'
    required: false
  email:
    description: 'set to override GITHUB_EMAIL in the merge commit'
    required: false
  PACKAGEJSON_DIR:
    description: 'Custom dir to the package'
    default: ''
    required: false
